site_name: pycomex
site_description: Documentation for the pycomex project
site_author: Your Name
docs_dir: docs

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.expand
    - toc.integrate

nav:
  - Introduction: introduction.md
  - Philosophy: philosophy.md
  - Basics:
      - Hooks: basics_hooks.md
      - Configuration Files: basics_config.md
  - Advanced Usage:
      - Writing Plugins: advanced_plugins.md
      - Plugin Hooks: advanced_hooks.md
  - Tools:
      - VSCode Extension: tools_vscode.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.arithmatex
